### ISSUE TITLE
Java method returning a `boolean`: in Julia, converted into UInt8? 

### ISSUE THREAD

**Issue by dourouc05** [JuliaInterop/JavaCall.jl#110]
In my code, I'm calling [this method](https://www.ibm.com/support/knowledgecenter/SSSA5P_12.10.0/ilog.odms.cpo.help/refjavacpoptimizer/html/ilog/cp/IloCP.html#solve()) with this code (`cp` being a Java object of type IloCP): 

```
r = jcall(cp, "solve", jboolean, ())
println(r)
println(typeof(r))
```

However, the result of this code is unexpectedly a `UInt8`, not a `Bool`: 

```
1
UInt8
```

I suppose this is a bug (usually, `jcall` returns the right type), but maybe I'm missing something? 

(Unfortunately, I'm calling a proprietary library, I'm pretty sure I cannot share the JAR. This is a library wrapping a C++ library, on top of that: it should be a pretty thin wrapper around the C++ version of the code.)

**Comment by aviks** [comment]
Ah, ILOG, a name I havent heard in a decade -- fun times 😂 

This seems to be as expected. Note this is basically C, with no native boolean type. Boolean in JNI is emulated by char. 

https://github.com/JuliaInterop/JavaCall.jl/blob/0ecb17e044212bf3b353937c837c79617e4aa87a/src/core.jl#L11

Formal spec is here: https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/types.html

Put it another way, JavaCall returns the nearest physically compatible Julia type, not the nearest semantic Julia type. The only exception to this is String, where we convert to a Julia String rather than returning a `Array{Uint8}`. It so happens that boolean is where this difference shows up the most, since for the integer or float primitive types, the nearest bits type is also semantically correct.

**Comment by aviks** [comment]
As an option, you can use the `JNI_TRUE` and `JNI_FALSE` constants to check the result. So, something like

```
if r == JavaCall.JNI_TRUE
    println("Model solved")
end
```

**Comment by dourouc05** [comment]
In that case, couldn't JavaCall bring a very slim abstraction on top of JNI and to convert the results to the closest Julia type? (After all, it's not called JNI.jl :)!)

**Comment by aviks** [comment]
Eh, maybe. All abstractions have costs, so it's debateable where to draw the line.

**Comment by dourouc05** [comment]
I don't think this would a high-cost abstraction: the context switch to the JVM is already quite costly, much higher than just casting a one-word integer. Or maybe `convert` can be used so that there is no cost for people not using this abstraction? But that would require a new type (and not just using Julia's Cuchar) to avoid converting to booleans things that should not…
