### ISSUE TITLE
Crashing after initialize call with JNA if System.gc is called

### ISSUE THREAD

**Issue by cnuernber** [JuliaInterop/JavaCall.jl#123]
Hey, I am playing with JNA bindings and consistently getting a crash on 1.4.2 if `jl_init__threading` is called at all and then followed with 1 or 2 System.gc() calls.

The crash I am seeing is:
```console
fatal: error thrown and no exception handler available.
ReadOnlyMemoryError()
```

We are setting up the system with the appropriate julia variables set:
https://github.com/cnuernber/julia-clj/blob/master/dockerfiles/Dockerfile#L32

Again, this is simply calling jl_init__threading and then (System.gc) a few times.

**Comment by mkitti** [comment]
Hi @cnuernber , JavaCall.jl may not be the best place for this issue. It sounds like you are trying to embed Julia into Java using JNA.

The issue is probably better posted on the Julia github itself: https://github.com/JuliaLang/julia

It does seem like this might require more interactive online debugging, so I also recommend the Julia Slack or Julia Zulip:
https://slackinvite.julialang.org/
https://julialang.zulipchat.com/#

You may also have an interest in https://github.com/rssdev10/julia4j

**Comment by cnuernber** [comment]
Thanks, that is great info :-).
